<?php

namespace Database\Seeders;

use App\Models\Lead;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin user or first user as fallback
        // For testing, use the currently logged in user or admin
        $adminUser = User::where('email', 'ombenifaraja@gmail.com')->first()
            ?? User::where('role', 'admin')->first()
            ?? User::first();

        if (!$adminUser) {
            $this->command->warn('No users found. Please run UserSeeder first.');
            return;
        }

        // Sample leads (not clients)
        $leads = [
            [
                'name' => 'John Mwangi',
                'position' => 'HR Manager',
                'company' => 'Tech Solutions Ltd',
                'email' => 'john.mwangi@techsolutions.co.ke',
                'phone' => '+254712345678',
                'mobile' => '+254712345678',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Technology',
                'added_by' => $adminUser->id,
                'status' => 'new_lead',
                'value' => 50000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(30),
                'notes' => 'Interested in pension scheme consultation for their employees.',
            ],
            [
                'name' => 'Sarah Wanjiku',
                'position' => 'Finance Director',
                'company' => 'Green Energy Corp',
                'email' => 'sarah.wanjiku@greenenergy.co.ke',
                'phone' => '+254723456789',
                'mobile' => '+254723456789',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Energy',
                'added_by' => $adminUser->id,
                'status' => 'initial_outreach',
                'value' => 75000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(45),
                'notes' => 'Initial contact made, waiting for response.',
            ],
            [
                'name' => 'David Ochieng',
                'position' => 'CEO',
                'company' => 'Manufacturing Industries',
                'email' => 'david.ochieng@manufacturing.co.ke',
                'phone' => '+254734567890',
                'mobile' => '+254734567890',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Manufacturing',
                'added_by' => $adminUser->id,
                'status' => 'follow_ups',
                'value' => 100000.00,
                'product' => 'Pension Fund Management',
                'expected_close_date' => now()->addDays(60),
                'notes' => 'Multiple follow-ups conducted, very interested.',
            ],
            [
                'name' => 'Mary Akinyi',
                'position' => 'Operations Manager',
                'company' => 'Logistics Pro',
                'email' => 'mary.akinyi@logisticspro.co.ke',
                'phone' => '+254745678901',
                'mobile' => '+254745678901',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Logistics',
                'added_by' => $adminUser->id,
                'status' => 'negotiations',
                'value' => 125000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(15),
                'notes' => 'In final negotiation phase, discussing terms.',
            ],
            [
                'name' => 'Peter Kamau',
                'position' => 'CFO',
                'company' => 'Financial Services Group',
                'email' => 'peter.kamau@fsg.co.ke',
                'phone' => '+254756789012',
                'mobile' => '+254756789012',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Finance',
                'added_by' => $adminUser->id,
                'status' => 'lost',
                'value' => 60000.00,
                'product' => 'Pension Scheme Audit',
                'actual_close_date' => now()->subDays(5),
                'lost_reason' => 'Decided to go with another provider due to pricing.',
                'notes' => 'Lost to competitor.',
            ],
        ];

        // Sample clients (won leads) - distributed across last 5 days for visualization
        $clients = [
            // 5 days ago - 3 sales
            [
                'name' => 'James Kariuki',
                'position' => 'Managing Director',
                'company' => 'Construction Masters',
                'email' => 'james.kariuki@constructionmasters.co.ke',
                'phone' => '+254767890123',
                'mobile' => '+254767890123',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Construction',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 50000.00,
                'product' => 'Pension Scheme Consultation, Retirement Planning Package',
                'actual_close_date' => now()->subDays(4),
                'won_at' => now()->subDays(4)->setTime(10, 30, 0),
                'is_client' => true,
                'notes' => 'Successfully converted to client.',
            ],
            [
                'name' => 'Alice Wambui',
                'position' => 'CEO',
                'company' => 'StartUp Ventures',
                'email' => 'alice.wambui@startup.co.ke',
                'phone' => '+254790123456',
                'mobile' => '+254790123456',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Technology',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 45000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(4),
                'won_at' => now()->subDays(4)->setTime(14, 15, 0),
                'is_client' => true,
                'notes' => 'Quick conversion from initial contact.',
            ],
            [
                'name' => 'Robert Maina',
                'position' => 'Finance Director',
                'company' => 'Export Solutions',
                'email' => 'robert.maina@export.co.ke',
                'phone' => '+254701234567',
                'mobile' => '+254701234567',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Export/Import',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 65000.00,
                'product' => 'Employee Benefits Package, Pension Fund Management',
                'actual_close_date' => now()->subDays(4),
                'won_at' => now()->subDays(4)->setTime(16, 45, 0),
                'is_client' => true,
                'notes' => 'Closed deal after detailed presentation.',
            ],

            // 4 days ago - 7 sales
            [
                'name' => 'Grace Njeri',
                'position' => 'HR Director',
                'company' => 'Healthcare Services',
                'email' => 'grace.njeri@healthcare.co.ke',
                'phone' => '+254778901234',
                'mobile' => '+254778901234',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Healthcare',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 75000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(9, 0, 0),
                'is_client' => true,
                'notes' => 'Client since last month.',
            ],
            [
                'name' => 'Catherine Mutua',
                'position' => 'CFO',
                'company' => 'Banking Solutions',
                'email' => 'catherine.mutua@banking.co.ke',
                'phone' => '+254712345678',
                'mobile' => '+254712345678',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Finance',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 90000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(11, 30, 0),
                'is_client' => true,
                'notes' => 'Large enterprise client.',
            ],
            [
                'name' => 'Daniel Omondi',
                'position' => 'Operations Manager',
                'company' => 'Transport Co',
                'email' => 'daniel.omondi@transport.co.ke',
                'phone' => '+254723456789',
                'mobile' => '+254723456789',
                'city' => 'Kisumu',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Transportation',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 55000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(13, 0, 0),
                'is_client' => true,
                'notes' => 'Impressed by our presentation.',
            ],
            [
                'name' => 'Elizabeth Wanjiru',
                'position' => 'Managing Partner',
                'company' => 'Legal Associates',
                'email' => 'elizabeth.wanjiru@legal.co.ke',
                'phone' => '+254734567890',
                'mobile' => '+254734567890',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Legal',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 70000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(14, 30, 0),
                'is_client' => true,
                'notes' => 'Professional services firm.',
            ],
            [
                'name' => 'Francis Kipchoge',
                'position' => 'CEO',
                'company' => 'Agriculture Holdings',
                'email' => 'francis.kipchoge@agri.co.ke',
                'phone' => '+254745678901',
                'mobile' => '+254745678901',
                'city' => 'Eldoret',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Agriculture',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 85000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(15, 45, 0),
                'is_client' => true,
                'notes' => 'Met at agricultural expo.',
            ],
            [
                'name' => 'Hannah Chebet',
                'position' => 'HR Manager',
                'company' => 'Hospitality Group',
                'email' => 'hannah.chebet@hospitality.co.ke',
                'phone' => '+254756789012',
                'mobile' => '+254756789012',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Hospitality',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 60000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(16, 20, 0),
                'is_client' => true,
                'notes' => 'Hotel chain client.',
            ],
            [
                'name' => 'Isaac Mutiso',
                'position' => 'Finance Manager',
                'company' => 'Tech Innovations',
                'email' => 'isaac.mutiso@techinno.co.ke',
                'phone' => '+254767890123',
                'mobile' => '+254767890123',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Technology',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 50000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(17, 0, 0),
                'is_client' => true,
                'notes' => 'Tech startup with growth potential.',
            ],

            // 3 days ago - 2 sales
            [
                'name' => 'Michael Otieno',
                'position' => 'Finance Manager',
                'company' => 'Retail Chain Ltd',
                'email' => 'michael.otieno@retailchain.co.ke',
                'phone' => '+254789012345',
                'mobile' => '+254789012345',
                'city' => 'Kisumu',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Retail',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 100000.00,
                'product' => 'Pension Fund Management, Pension Scheme Consultation',
                'actual_close_date' => now()->subDays(2),
                'won_at' => now()->subDays(2)->setTime(10, 0, 0),
                'is_client' => true,
                'notes' => 'Long-term client, very satisfied.',
            ],
            [
                'name' => 'Jane Auma',
                'position' => 'COO',
                'company' => 'Manufacturing Ltd',
                'email' => 'jane.auma@manufacturing.co.ke',
                'phone' => '+254791234567',
                'mobile' => '+254791234567',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Manufacturing',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 95000.00,
                'product' => 'Employee Benefits Package, Retirement Planning Package',
                'actual_close_date' => now()->subDays(2),
                'won_at' => now()->subDays(2)->setTime(15, 30, 0),
                'is_client' => true,
                'notes' => 'Large manufacturing client.',
            ],

            // 2 days ago - 12 sales
            [
                'name' => 'Kevin Ndungu',
                'position' => 'Director',
                'company' => 'Education Services',
                'email' => 'kevin.ndungu@education.co.ke',
                'phone' => '+254702345678',
                'mobile' => '+254702345678',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Education',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 55000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(9, 15, 0),
                'is_client' => true,
                'notes' => 'Educational institution.',
            ],
            [
                'name' => 'Linda Nyambura',
                'position' => 'CFO',
                'company' => 'Media House',
                'email' => 'linda.nyambura@media.co.ke',
                'phone' => '+254713456789',
                'mobile' => '+254713456789',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Media',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 70000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(10, 0, 0),
                'is_client' => true,
                'notes' => 'Broadcasting company.',
            ],
            [
                'name' => 'Moses Kamau',
                'position' => 'GM',
                'company' => 'Real Estate Developers',
                'email' => 'moses.kamau@realestate.co.ke',
                'phone' => '+254724567890',
                'mobile' => '+254724567890',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Real Estate',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 120000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(10, 45, 0),
                'is_client' => true,
                'notes' => 'High-value real estate client.',
            ],
            [
                'name' => 'Nancy Jepkosgei',
                'position' => 'HR Director',
                'company' => 'Telecom Services',
                'email' => 'nancy.jepkosgei@telecom.co.ke',
                'phone' => '+254735678901',
                'mobile' => '+254735678901',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Telecommunications',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 110000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(11, 30, 0),
                'is_client' => true,
                'notes' => 'Telecommunications provider.',
            ],
            [
                'name' => 'Oscar Wekesa',
                'position' => 'CEO',
                'company' => 'Consulting Firm',
                'email' => 'oscar.wekesa@consulting.co.ke',
                'phone' => '+254746789012',
                'mobile' => '+254746789012',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Consulting',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 75000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(12, 0, 0),
                'is_client' => true,
                'notes' => 'Management consulting firm.',
            ],
            [
                'name' => 'Patricia Adhiambo',
                'position' => 'Finance Director',
                'company' => 'Insurance Co',
                'email' => 'patricia.adhiambo@insurance.co.ke',
                'phone' => '+254757890123',
                'mobile' => '+254757890123',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Insurance',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 95000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(13, 15, 0),
                'is_client' => true,
                'notes' => 'Insurance sector client.',
            ],
            [
                'name' => 'Quinn Okoth',
                'position' => 'Managing Director',
                'company' => 'Pharmaceutical Ltd',
                'email' => 'quinn.okoth@pharma.co.ke',
                'phone' => '+254768901234',
                'mobile' => '+254768901234',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Healthcare',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 85000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(14, 0, 0),
                'is_client' => true,
                'notes' => 'Healthcare sector.',
            ],
            [
                'name' => 'Rachel Waweru',
                'position' => 'COO',
                'company' => 'Aviation Services',
                'email' => 'rachel.waweru@aviation.co.ke',
                'phone' => '+254779012345',
                'mobile' => '+254779012345',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Aviation',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 130000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(14, 45, 0),
                'is_client' => true,
                'notes' => 'Aviation industry client.',
            ],
            [
                'name' => 'Samuel Kiprotich',
                'position' => 'HR Manager',
                'company' => 'Security Services',
                'email' => 'samuel.kiprotich@security.co.ke',
                'phone' => '+254780123456',
                'mobile' => '+254780123456',
                'city' => 'Nakuru',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Security',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 65000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(15, 30, 0),
                'is_client' => true,
                'notes' => 'Security firm.',
            ],
            [
                'name' => 'Teresa Muthoni',
                'position' => 'Finance Manager',
                'company' => 'Energy Solutions',
                'email' => 'teresa.muthoni@energy.co.ke',
                'phone' => '+254791234567',
                'mobile' => '+254791234567',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Energy',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 105000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(16, 0, 0),
                'is_client' => true,
                'notes' => 'Renewable energy company.',
            ],
            [
                'name' => 'Vincent Onyango',
                'position' => 'CEO',
                'company' => 'Mining Corporation',
                'email' => 'vincent.onyango@mining.co.ke',
                'phone' => '+254702345678',
                'mobile' => '+254702345678',
                'city' => 'Eldoret',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Mining',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 140000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(16, 45, 0),
                'is_client' => true,
                'notes' => 'Mining sector client.',
            ],
            [
                'name' => 'Winnie Nyokabi',
                'position' => 'CFO',
                'company' => 'Water Services',
                'email' => 'winnie.nyokabi@water.co.ke',
                'phone' => '+254713456789',
                'mobile' => '+254713456789',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Utilities',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 80000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(17, 15, 0),
                'is_client' => true,
                'notes' => 'Utilities sector.',
            ],

            // Today - 20 sales
            [
                'name' => 'Xavier Mugo',
                'position' => 'Director',
                'company' => 'Fashion Retail',
                'email' => 'xavier.mugo@fashion.co.ke',
                'phone' => '+254724567890',
                'mobile' => '+254724567890',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Retail',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 55000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(8, 0, 0),
                'is_client' => true,
                'notes' => 'Retail fashion chain.',
            ],
            [
                'name' => 'Yvonne Nekesa',
                'position' => 'GM',
                'company' => 'Tourism Agency',
                'email' => 'yvonne.nekesa@tourism.co.ke',
                'phone' => '+254735678901',
                'mobile' => '+254735678901',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Tourism',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 60000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(8, 30, 0),
                'is_client' => true,
                'notes' => 'Travel and tourism.',
            ],
            [
                'name' => 'Zachary Kimani',
                'position' => 'CEO',
                'company' => 'Logistics Hub',
                'email' => 'zachary.kimani@logistics.co.ke',
                'phone' => '+254746789012',
                'mobile' => '+254746789012',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Logistics',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 90000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(9, 0, 0),
                'is_client' => true,
                'notes' => 'Logistics and warehousing.',
            ],
            [
                'name' => 'Angela Wangari',
                'position' => 'CFO',
                'company' => 'Food Processing',
                'email' => 'angela.wangari@foodproc.co.ke',
                'phone' => '+254757890123',
                'mobile' => '+254757890123',
                'city' => 'Thika',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Food & Beverage',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 75000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(9, 30, 0),
                'is_client' => true,
                'notes' => 'Food manufacturing.',
            ],
            [
                'name' => 'Brian Ochieng',
                'position' => 'Operations Manager',
                'company' => 'E-commerce Platform',
                'email' => 'brian.ochieng@ecommerce.co.ke',
                'phone' => '+254768901234',
                'mobile' => '+254768901234',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Technology',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 65000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(10, 0, 0),
                'is_client' => true,
                'notes' => 'Online retail platform.',
            ],
            [
                'name' => 'Caroline Achieng',
                'position' => 'HR Director',
                'company' => 'Engineering Firm',
                'email' => 'caroline.achieng@engineering.co.ke',
                'phone' => '+254779012345',
                'mobile' => '+254779012345',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Engineering',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 95000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(10, 30, 0),
                'is_client' => true,
                'notes' => 'Civil engineering company.',
            ],
            [
                'name' => 'Dennis Wanjala',
                'position' => 'Managing Director',
                'company' => 'Chemical Industries',
                'email' => 'dennis.wanjala@chemicals.co.ke',
                'phone' => '+254780123456',
                'mobile' => '+254780123456',
                'city' => 'Eldoret',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Manufacturing',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 110000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(11, 0, 0),
                'is_client' => true,
                'notes' => 'Chemical manufacturing.',
            ],
            [
                'name' => 'Edith Mwikali',
                'position' => 'Finance Manager',
                'company' => 'Publishing House',
                'email' => 'edith.mwikali@publishing.co.ke',
                'phone' => '+254791234567',
                'mobile' => '+254791234567',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Media',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 70000.00,
                'product' => 'Pension Fund Management, Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(11, 30, 0),
                'is_client' => true,
                'notes' => 'Media and publishing.',
            ],
            [
                'name' => 'Felix Mwangi',
                'position' => 'CEO',
                'company' => 'Software Solutions',
                'email' => 'felix.mwangi@software.co.ke',
                'phone' => '+254702345678',
                'mobile' => '+254702345678',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 85000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(12, 0, 0),
                'is_client' => true,
                'notes' => 'Software development company.',
            ],
            [
                'name' => 'Gloria Njoki',
                'position' => 'COO',
                'company' => 'Textile Mills',
                'email' => 'gloria.njoki@textiles.co.ke',
                'phone' => '+254713456789',
                'mobile' => '+254713456789',
                'city' => 'Thika',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 100000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(12, 30, 0),
                'is_client' => true,
                'notes' => 'Textile manufacturing.',
            ],
            [
                'name' => 'Henry Kariuki',
                'position' => 'Finance Director',
                'company' => 'Automotive Dealers',
                'email' => 'henry.kariuki@automotive.co.ke',
                'phone' => '+254724567890',
                'mobile' => '+254724567890',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Automotive',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 115000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(13, 0, 0),
                'is_client' => true,
                'notes' => 'Car dealership chain.',
            ],
            [
                'name' => 'Irene Wanjiru',
                'position' => 'HR Manager',
                'company' => 'Electronics Store',
                'email' => 'irene.wanjiru@electronics.co.ke',
                'phone' => '+254735678901',
                'mobile' => '+254735678901',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Retail',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 60000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(13, 30, 0),
                'is_client' => true,
                'notes' => 'Electronics retail.',
            ],
            [
                'name' => 'Joseph Mutua',
                'position' => 'Managing Director',
                'company' => 'Construction Ltd',
                'email' => 'joseph.mutua@construction.co.ke',
                'phone' => '+254746789012',
                'mobile' => '+254746789012',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Construction',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 125000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(14, 0, 0),
                'is_client' => true,
                'notes' => 'Construction and development.',
            ],
            [
                'name' => 'Kagiso Muthoni',
                'position' => 'CFO',
                'company' => 'Sports Management',
                'email' => 'kagiso.muthoni@sports.co.ke',
                'phone' => '+254757890123',
                'mobile' => '+254757890123',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Sports & Entertainment',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 70000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(14, 30, 0),
                'is_client' => true,
                'notes' => 'Sports and entertainment.',
            ],
            [
                'name' => 'Lilian Akinyi',
                'position' => 'Operations Manager',
                'company' => 'Freight Forwarders',
                'email' => 'lilian.akinyi@freight.co.ke',
                'phone' => '+254768901234',
                'mobile' => '+254768901234',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Logistics',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 80000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(15, 0, 0),
                'is_client' => true,
                'notes' => 'Freight and shipping.',
            ],
            [
                'name' => 'Martin Odhiambo',
                'position' => 'CEO',
                'company' => 'Furniture Makers',
                'email' => 'martin.odhiambo@furniture.co.ke',
                'phone' => '+254779012345',
                'mobile' => '+254779012345',
                'city' => 'Kisumu',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Manufacturing',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 65000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(15, 30, 0),
                'is_client' => true,
                'notes' => 'Furniture manufacturing.',
            ],
            [
                'name' => 'Naomi Cherotich',
                'position' => 'Finance Director',
                'company' => 'Accounting Firm',
                'email' => 'naomi.cherotich@accounting.co.ke',
                'phone' => '+254780123456',
                'mobile' => '+254780123456',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Finance',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 90000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(16, 0, 0),
                'is_client' => true,
                'notes' => 'Professional services.',
            ],
            [
                'name' => 'Oliver Muema',
                'position' => 'HR Director',
                'company' => 'Packaging Solutions',
                'email' => 'oliver.muema@packaging.co.ke',
                'phone' => '+254791234567',
                'mobile' => '+254791234567',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Manufacturing',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 75000.00,
                'product' => 'Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(16, 30, 0),
                'is_client' => true,
                'notes' => 'Packaging industry.',
            ],
            [
                'name' => 'Pauline Wangui',
                'position' => 'Managing Partner',
                'company' => 'Audit Services',
                'email' => 'pauline.wangui@audit.co.ke',
                'phone' => '+254702345678',
                'mobile' => '+254702345678',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Finance',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 105000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(17, 0, 0),
                'is_client' => true,
                'notes' => 'Audit and compliance.',
            ],
            [
                'name' => 'Quincy Omondi',
                'position' => 'COO',
                'company' => 'Beverage Company',
                'email' => 'quincy.omondi@beverage.co.ke',
                'phone' => '+254713456789',
                'mobile' => '+254713456789',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Food & Beverage',
                'added_by' => $adminUser->id,
                'status' => 'won',
                'value' => 95000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(17, 30, 0),
                'is_client' => true,
                'notes' => 'Beverage manufacturing.',
            ],
        ];

        // Create leads
        foreach ($leads as $leadData) {
            $lead = Lead::firstOrCreate(
                ['email' => $leadData['email']],
                $leadData
            );

            // Add products to pivot table if product field exists
            if (isset($leadData['product']) && !empty($leadData['product'])) {
                $this->attachProductsToLead($lead, $leadData['product'], $lead->created_at);
            }
        }

        // Create clients
        foreach ($clients as $clientData) {
            $client = Lead::firstOrCreate(
                ['email' => $clientData['email']],
                $clientData
            );

            // Add products to pivot table if product field exists
            if (isset($clientData['product']) && !empty($clientData['product'])) {
                $this->attachProductsToLead($client, $clientData['product'], $client->created_at);
            }
        }

        // Additional leads for existing users
        // Get or create additional users and store their IDs
        $managerUser = User::firstOrCreate(
            ['email' => 'manager@zuritconsulting.com'],
            [
                'name' => 'Manager User',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'is_active' => true,
            ]
        );

        $salesUser = User::firstOrCreate(
            ['email' => 'sales@zuritconsulting.com'],
            [
                'name' => 'Sales User',
                'password' => bcrypt('password'),
                'role' => 'team_member',
                'is_active' => true,
            ]
        );

        // Get user ID 3 or use admin user as fallback
        $user3 = User::find(3) ?? $adminUser;
        $user4 = $managerUser;
        $user5 = $salesUser;

        // Additional leads for User ID 3 (10 leads)
        $this->command->info('Creating leads for User ID ' . $user3->id . '...');
        $user3Leads = [
            [
                'name' => 'Alex Kimathi',
                'position' => 'CEO',
                'company' => 'Digital Marketing Agency',
                'email' => 'alex.kimathi@digitalagency.co.ke',
                'phone' => '+254720111222',
                'mobile' => '+254720111222',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Technology',
                'added_by' => $user5->id,
                'status' => 'new_lead',
                'value' => 60000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(20),
                'notes' => 'Interested in group pension plans.',
            ],
            [
                'name' => 'Betty Wambui',
                'position' => 'HR Manager',
                'company' => 'Retail Solutions Ltd',
                'email' => 'betty.wambui@retail.co.ke',
                'phone' => '+254720222333',
                'mobile' => '+254720222333',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Retail',
                'added_by' => $user5->id,
                'status' => 'initial_outreach',
                'value' => 85000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(30),
                'notes' => 'Follow-up scheduled next week.',
            ],
            [
                'name' => 'Charles Omondi',
                'position' => 'Finance Director',
                'company' => 'Construction Plus',
                'email' => 'charles.omondi@construction.co.ke',
                'phone' => '+254720333444',
                'mobile' => '+254720333444',
                'city' => 'Kisumu',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Construction',
                'added_by' => $user5->id,
                'status' => 'follow_ups',
                'value' => 120000.00,
                'product' => 'Pension Fund Management',
                'expected_close_date' => now()->addDays(25),
                'notes' => 'Reviewing proposal documents.',
            ],
            [
                'name' => 'Diana Njeri',
                'position' => 'Operations Manager',
                'company' => 'Logistics Express',
                'email' => 'diana.njeri@logistics.co.ke',
                'phone' => '+254720444555',
                'mobile' => '+254720444555',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Logistics',
                'added_by' => $user5->id,
                'status' => 'negotiations',
                'value' => 95000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(10),
                'notes' => 'Negotiating pricing terms.',
            ],
            [
                'name' => 'Edward Mwangi',
                'position' => 'Managing Director',
                'company' => 'Tech Innovators',
                'email' => 'edward.mwangi@techinnovators.co.ke',
                'phone' => '+254720555666',
                'mobile' => '+254720555666',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Technology',
                'added_by' => $user5->id,
                'status' => 'won',
                'value' => 150000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(2),
                'won_at' => now()->subDays(2)->setTime(11, 0, 0),
                'is_client' => true,
                'notes' => 'Large tech company deal.',
            ],
            [
                'name' => 'Faith Akinyi',
                'position' => 'CFO',
                'company' => 'Manufacturing Corp',
                'email' => 'faith.akinyi@mfgcorp.co.ke',
                'phone' => '+254720666777',
                'mobile' => '+254720666777',
                'city' => 'Nakuru',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Manufacturing',
                'added_by' => $user5->id,
                'status' => 'won',
                'value' => 110000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(14, 30, 0),
                'is_client' => true,
                'notes' => 'Manufacturing sector client.',
            ],
            [
                'name' => 'George Kamau',
                'position' => 'HR Director',
                'company' => 'Healthcare Plus',
                'email' => 'george.kamau@healthcareplus.co.ke',
                'phone' => '+254720777888',
                'mobile' => '+254720777888',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Healthcare',
                'added_by' => $user5->id,
                'status' => 'new_lead',
                'value' => 75000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(35),
                'notes' => 'Hospital group inquiry.',
            ],
            [
                'name' => 'Hannah Wanjiku',
                'position' => 'CEO',
                'company' => 'Financial Advisors Ltd',
                'email' => 'hannah.wanjiku@finadvisors.co.ke',
                'phone' => '+254720888999',
                'mobile' => '+254720888999',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Finance',
                'added_by' => $user5->id,
                'status' => 'initial_outreach',
                'value' => 90000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(40),
                'notes' => 'Professional services firm.',
            ],
            [
                'name' => 'Ian Ochieng',
                'position' => 'Finance Manager',
                'company' => 'Export Trading Co',
                'email' => 'ian.ochieng@export.co.ke',
                'phone' => '+254720999000',
                'mobile' => '+254720999000',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Export/Import',
                'added_by' => $user5->id,
                'status' => 'follow_ups',
                'value' => 105000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(22),
                'notes' => 'Export company interested.',
            ],
            [
                'name' => 'Jane Mutua',
                'position' => 'Operations Director',
                'company' => 'Tourism Services',
                'email' => 'jane.mutua@tourism.co.ke',
                'phone' => '+254721000111',
                'mobile' => '+254721000111',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Tourism',
                'added_by' => $user5->id,
                'status' => 'won',
                'value' => 80000.00,
                'product' => 'Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(10, 15, 0),
                'is_client' => true,
                'notes' => 'Tourism sector client.',
            ],
        ];

        foreach ($user3Leads as $leadData) {
            $lead = Lead::firstOrCreate(
                ['email' => $leadData['email']],
                $leadData
            );

            // Add products to pivot table if product field exists
            if (isset($leadData['product']) && !empty($leadData['product'])) {
                $this->attachProductsToLead($lead, $leadData['product'], $lead->created_at);
            }
        }

        // Additional leads for User ID 4 (10 leads)
        $this->command->info('Creating leads for User ID ' . $user4->id . '...');
        $user4Leads = [
            [
                'name' => 'Kevin Musyoka',
                'position' => 'CEO',
                'company' => 'Software Developers',
                'email' => 'kevin.musyoka@softdev.co.ke',
                'phone' => '+254721111222',
                'mobile' => '+254721111222',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Technology',
                'added_by' => $user3->id,
                'status' => 'new_lead',
                'value' => 70000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(28),
                'notes' => 'Tech startup inquiry.',
            ],
            [
                'name' => 'Lucy Njoroge',
                'position' => 'HR Manager',
                'company' => 'Property Developers',
                'email' => 'lucy.njoroge@property.co.ke',
                'phone' => '+254721222333',
                'mobile' => '+254721222333',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Real Estate',
                'added_by' => $user3->id,
                'status' => 'initial_outreach',
                'value' => 130000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(35),
                'notes' => 'Real estate developer.',
            ],
            [
                'name' => 'Mark Wekesa',
                'position' => 'Finance Director',
                'company' => 'Transport Solutions',
                'email' => 'mark.wekesa@transport.co.ke',
                'phone' => '+254721333444',
                'mobile' => '+254721333444',
                'city' => 'Kisumu',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Transportation',
                'added_by' => $user3->id,
                'status' => 'follow_ups',
                'value' => 88000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(18),
                'notes' => 'Fleet management company.',
            ],
            [
                'name' => 'Nancy Adhiambo',
                'position' => 'Managing Director',
                'company' => 'Education Services',
                'email' => 'nancy.adhiambo@eduservices.co.ke',
                'phone' => '+254721444555',
                'mobile' => '+254721444555',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Education',
                'added_by' => $user3->id,
                'status' => 'negotiations',
                'value' => 95000.00,
                'product' => 'Pension Fund Management',
                'expected_close_date' => now()->addDays(12),
                'notes' => 'School management group.',
            ],
            [
                'name' => 'Oscar Kipchoge',
                'position' => 'CFO',
                'company' => 'Agriculture Holdings',
                'email' => 'oscar.kipchoge@agriholdings.co.ke',
                'phone' => '+254721555666',
                'mobile' => '+254721555666',
                'city' => 'Eldoret',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Agriculture',
                'added_by' => $user3->id,
                'status' => 'won',
                'value' => 125000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(3),
                'won_at' => now()->subDays(3)->setTime(15, 0, 0),
                'is_client' => true,
                'notes' => 'Large agricultural firm.',
            ],
            [
                'name' => 'Patricia Nyambura',
                'position' => 'Operations Manager',
                'company' => 'Media Group',
                'email' => 'patricia.nyambura@mediagroup.co.ke',
                'phone' => '+254721666777',
                'mobile' => '+254721666777',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Media',
                'added_by' => $user3->id,
                'status' => 'won',
                'value' => 100000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(16, 45, 0),
                'is_client' => true,
                'notes' => 'Broadcasting company.',
            ],
            [
                'name' => 'Quincy Otieno',
                'position' => 'HR Director',
                'company' => 'Insurance Brokers',
                'email' => 'quincy.otieno@insurance.co.ke',
                'phone' => '+254721777888',
                'mobile' => '+254721777888',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Insurance',
                'added_by' => $user3->id,
                'status' => 'new_lead',
                'value' => 65000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(32),
                'notes' => 'Insurance sector inquiry.',
            ],
            [
                'name' => 'Rachel Chebet',
                'position' => 'CEO',
                'company' => 'Engineering Consultants',
                'email' => 'rachel.chebet@engineering.co.ke',
                'phone' => '+254721888999',
                'mobile' => '+254721888999',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Engineering',
                'added_by' => $user3->id,
                'status' => 'initial_outreach',
                'value' => 110000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(27),
                'notes' => 'Civil engineering firm.',
            ],
            [
                'name' => 'Samuel Maina',
                'position' => 'Finance Manager',
                'company' => 'Pharmaceutical Supplies',
                'email' => 'samuel.maina@pharmasupply.co.ke',
                'phone' => '+254721999000',
                'mobile' => '+254721999000',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Healthcare',
                'added_by' => $user3->id,
                'status' => 'follow_ups',
                'value' => 92000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(20),
                'notes' => 'Healthcare sector.',
            ],
            [
                'name' => 'Teresa Wangui',
                'position' => 'Operations Director',
                'company' => 'Retail Chain',
                'email' => 'teresa.wangui@retailchain.co.ke',
                'phone' => '+254722000111',
                'mobile' => '+254722000111',
                'city' => 'Nakuru',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Retail',
                'added_by' => $user3->id,
                'status' => 'won',
                'value' => 115000.00,
                'product' => 'Pension Fund Management, Employee Benefits Package, Retirement Planning Package',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(13, 20, 0),
                'is_client' => true,
                'notes' => 'Retail chain client.',
            ],
        ];

        foreach ($user3Leads as $leadData) {
            $lead = Lead::firstOrCreate(
                ['email' => $leadData['email']],
                $leadData
            );

            // Add products to pivot table if product field exists
            if (isset($leadData['product']) && !empty($leadData['product'])) {
                $this->attachProductsToLead($lead, $leadData['product'], $lead->created_at);
            }
        }

        foreach ($user4Leads as $leadData) {
            $lead = Lead::firstOrCreate(
                ['email' => $leadData['email']],
                $leadData
            );

            // Add products to pivot table if product field exists
            if (isset($leadData['product']) && !empty($leadData['product'])) {
                $this->attachProductsToLead($lead, $leadData['product'], $lead->created_at);
            }
        }

        // Additional leads for User ID 5 (10 leads)
        $this->command->info('Creating leads for User ID ' . $user5->id . '...');
        $user5Leads = [
            [
                'name' => 'Victor Kamau',
                'position' => 'CEO',
                'company' => 'Automotive Services',
                'email' => 'victor.kamau@automotive.co.ke',
                'phone' => '+254722111222',
                'mobile' => '+254722111222',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Automotive',
                'added_by' => $user5->id,
                'status' => 'new_lead',
                'value' => 85000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(25),
                'notes' => 'Car dealership group.',
            ],
            [
                'name' => 'Winnie Achieng',
                'position' => 'HR Manager',
                'company' => 'Security Systems',
                'email' => 'winnie.achieng@security.co.ke',
                'phone' => '+254722222333',
                'mobile' => '+254722222333',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Security',
                'added_by' => $user5->id,
                'status' => 'initial_outreach',
                'value' => 70000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(30),
                'notes' => 'Security firm interested.',
            ],
            [
                'name' => 'Xavier Nyaga',
                'position' => 'Finance Director',
                'company' => 'Mining Corporation',
                'email' => 'xavier.nyaga@mining.co.ke',
                'phone' => '+254722333444',
                'mobile' => '+254722333444',
                'city' => 'Eldoret',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Mining',
                'added_by' => $user5->id,
                'status' => 'follow_ups',
                'value' => 140000.00,
                'product' => 'Pension Fund Management',
                'expected_close_date' => now()->addDays(22),
                'notes' => 'Mining sector inquiry.',
            ],
            [
                'name' => 'Yvonne Wambua',
                'position' => 'Managing Director',
                'company' => 'Hotel Chain',
                'email' => 'yvonne.wambua@hotelchain.co.ke',
                'phone' => '+254722444555',
                'mobile' => '+254722444555',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Hospitality',
                'added_by' => $user5->id,
                'status' => 'negotiations',
                'value' => 120000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(15),
                'notes' => 'Hospitality group.',
            ],
            [
                'name' => 'Zack Omondi',
                'position' => 'CFO',
                'company' => 'Water Utilities',
                'email' => 'zack.omondi@water.co.ke',
                'phone' => '+254722555666',
                'mobile' => '+254722555666',
                'city' => 'Kisumu',
                'country' => 'Kenya',
                'source' => 'Trade Show',
                'sector' => 'Utilities',
                'added_by' => $user5->id,
                'status' => 'won',
                'value' => 135000.00,
                'product' => 'Employee Benefits Package',
                'actual_close_date' => now()->subDays(2),
                'won_at' => now()->subDays(2)->setTime(12, 30, 0),
                'is_client' => true,
                'notes' => 'Public utilities sector.',
            ],
            [
                'name' => 'Alice Muthoni',
                'position' => 'Operations Manager',
                'company' => 'Telecommunications',
                'email' => 'alice.muthoni@telecom.co.ke',
                'phone' => '+254722666777',
                'mobile' => '+254722666777',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Website',
                'sector' => 'Telecommunications',
                'added_by' => $user5->id,
                'status' => 'won',
                'value' => 145000.00,
                'product' => 'Pension Fund Management',
                'actual_close_date' => now()->subDays(1),
                'won_at' => now()->subDays(1)->setTime(11, 15, 0),
                'is_client' => true,
                'notes' => 'Telecom provider.',
            ],
            [
                'name' => 'Brian Kimani',
                'position' => 'HR Director',
                'company' => 'Chemical Industries',
                'email' => 'brian.kimani@chemicals.co.ke',
                'phone' => '+254722777888',
                'mobile' => '+254722777888',
                'city' => 'Thika',
                'country' => 'Kenya',
                'source' => 'Referral',
                'sector' => 'Manufacturing',
                'added_by' => $user5->id,
                'status' => 'new_lead',
                'value' => 95000.00,
                'product' => 'Pension Scheme Consultation',
                'expected_close_date' => now()->addDays(33),
                'notes' => 'Chemical manufacturing.',
            ],
            [
                'name' => 'Catherine Njoki',
                'position' => 'CEO',
                'company' => 'Legal Services',
                'email' => 'catherine.njoki@legal.co.ke',
                'phone' => '+254722888999',
                'mobile' => '+254722888999',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'Cold Call',
                'sector' => 'Legal',
                'added_by' => $user5->id,
                'status' => 'initial_outreach',
                'value' => 78000.00,
                'product' => 'Retirement Planning Package',
                'expected_close_date' => now()->addDays(38),
                'notes' => 'Law firm partnership.',
            ],
            [
                'name' => 'Dennis Ochieng',
                'position' => 'Finance Manager',
                'company' => 'Energy Solutions',
                'email' => 'dennis.ochieng@energy.co.ke',
                'phone' => '+254722999000',
                'mobile' => '+254722999000',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'source' => 'LinkedIn',
                'sector' => 'Energy',
                'added_by' => $user5->id,
                'status' => 'follow_ups',
                'value' => 105000.00,
                'product' => 'Employee Benefits Package',
                'expected_close_date' => now()->addDays(24),
                'notes' => 'Renewable energy company.',
            ],
            [
                'name' => 'Elizabeth Wanjiru',
                'position' => 'Operations Director',
                'company' => 'Aviation Maintenance',
                'email' => 'elizabeth.wanjiru@aviation.co.ke',
                'phone' => '+254723000111',
                'mobile' => '+254723000111',
                'city' => 'Mombasa',
                'country' => 'Kenya',
                'source' => 'Email Campaign',
                'sector' => 'Aviation',
                'added_by' => $user5->id,
                'status' => 'won',
                'value' => 155000.00,
                'product' => 'Pension Fund Management, Pension Scheme Consultation',
                'actual_close_date' => now(),
                'won_at' => now()->setTime(15, 45, 0),
                'is_client' => true,
                'notes' => 'Aviation sector client.',
            ],
        ];

        foreach ($user5Leads as $leadData) {
            $lead = Lead::firstOrCreate(
                ['email' => $leadData['email']],
                $leadData
            );

            // Add products to pivot table if product field exists
            if (isset($leadData['product']) && !empty($leadData['product'])) {
                $this->attachProductsToLead($lead, $leadData['product'], $lead->created_at);
            }
        }

        $this->command->info('All leads seeded successfully!');
    }

    /**
     * Attach products to a lead by parsing product string and creating pivot table entries.
     *
     * @param Lead $lead
     * @param string $productString Comma-separated product names
     * @param \Carbon\Carbon|null $enrolledAt
     * @return void
     */
    private function attachProductsToLead(Lead $lead, string $productString, $enrolledAt = null): void
    {
        if (empty($productString)) {
            return;
        }

        // Split product string by comma
        $productNames = array_map('trim', explode(',', $productString));
        $productNames = array_filter($productNames); // Remove empty values

        foreach ($productNames as $productName) {
            // Try to find matching product in products table
            $product = Product::where('name', $productName)->first();

            // Check if this relationship already exists
            $exists = DB::table('lead_product')
                ->where('lead_id', $lead->id)
                ->where(function ($query) use ($product, $productName) {
                    if ($product) {
                        $query->where('product_id', $product->id);
                    } else {
                        $query->whereNull('product_id')
                            ->where('product_name', $productName);
                    }
                })
                ->exists();

            if (!$exists) {
                // Insert into pivot table
                DB::table('lead_product')->insert([
                    'lead_id' => $lead->id,
                    'product_id' => $product ? $product->id : null,
                    'product_name' => $product ? null : $productName, // Store name if product doesn't exist
                    'enrolled_at' => $enrolledAt ?? now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
